import type { CalcInputs, CalcResult } from './magloop';
import { CONDUCTORS } from './constants';

export function generateNecFile(p: CalcInputs, r: CalcResult): string {
  const lines: string[] = [];
  lines.push(`CM Generated by MagLoop HamPro V9.0`);
  lines.push(`CM Frequency: ${p.fMHz} MHz`);
  lines.push(`CM Shape: ${p.shape}`);
  lines.push(`CM Loop Diameter/Side: ${p.loopDiameterM} m`);
  lines.push(`CE`);

  const cond = CONDUCTORS[p.conductorId] ?? CONDUCTORS['cu_tube_22'];
  const rCond = cond.d_equiv_m / 2;

  // Model the loop in the X-Z plane (vertical loop)
  if (p.shape === 'circle') {
    const S = 16; // 16-sided polygon
    const radius = p.loopDiameterM / 2;
    const centerZ = p.height + radius;

    for (let i = 1; i <= S; i++) {
      const a1 = (2 * Math.PI * (i - 1)) / S;
      const a2 = (2 * Math.PI * i) / S;
      
      const x1 = (radius * Math.cos(a1)).toFixed(4);
      const z1 = (centerZ + radius * Math.sin(a1)).toFixed(4);
      const x2 = (radius * Math.cos(a2)).toFixed(4);
      const z2 = (centerZ + radius * Math.sin(a2)).toFixed(4);
      
      // GW tag segs x1 y1 z1 x2 y2 z2 radius
      // Using 3 segments per wire for smooth MoM calculations
      lines.push(`GW  ${i}  3  ${x1}  0.0000  ${z1}  ${x2}  0.0000  ${z2}  ${rCond.toFixed(5)}`);
    }
    
    lines.push(`GE  1`);
    
    // EX card: Voltage source at the bottom (wire 13, segment 2)
    lines.push(`EX  0  13  2  0  1.0  0.0`);
    
    // LD card: Capacitor load at the top (wire 5, segment 2)
    lines.push(`LD  0  5  2  2  0.0  0.0  ${(r.CpF * 1e-12).toExponential(5)}`);
  } else {
    // Square loop
    const side = p.loopDiameterM;
    const halfSide = side / 2;
    
    const zBottom = p.height;
    const zTop = p.height + side;
    
    // GW tag segs x1 y1 z1 x2 y2 z2 radius
    // 9 segments per side
    lines.push(`GW  1  9  ${(-halfSide).toFixed(4)}  0.0000  ${zBottom.toFixed(4)}  ${halfSide.toFixed(4)}  0.0000  ${zBottom.toFixed(4)}  ${rCond.toFixed(5)}`);
    lines.push(`GW  2  9  ${halfSide.toFixed(4)}  0.0000  ${zBottom.toFixed(4)}  ${halfSide.toFixed(4)}  0.0000  ${zTop.toFixed(4)}  ${rCond.toFixed(5)}`);
    lines.push(`GW  3  9  ${halfSide.toFixed(4)}  0.0000  ${zTop.toFixed(4)}  ${(-halfSide).toFixed(4)}  0.0000  ${zTop.toFixed(4)}  ${rCond.toFixed(5)}`);
    lines.push(`GW  4  9  ${(-halfSide).toFixed(4)}  0.0000  ${zTop.toFixed(4)}  ${(-halfSide).toFixed(4)}  0.0000  ${zBottom.toFixed(4)}  ${rCond.toFixed(5)}`);
    
    lines.push(`GE  1`);
    
    // Source: Bottom wire (wire 1, segment 5)
    lines.push(`EX  0  1  5  0  1.0  0.0`);
    
    // Load (capacitor): Top wire (wire 3, segment 5)
    lines.push(`LD  0  3  5  5  0.0  0.0  ${(r.CpF * 1e-12).toExponential(5)}`);
  }

  // Frequency
  lines.push(`FR  0  1  0  0  ${p.fMHz}  0`);
  
  // Ground
  if (p.groundType === 'perfect') {
    lines.push(`GN  1  0  0  0  0.0  0.0`);
  } else if (p.groundType === 'good') {
    lines.push(`GN  2  0  0  0  13.0  0.005`);
  } else if (p.groundType === 'poor') {
    lines.push(`GN  2  0  0  0  5.0  0.001`);
  } else {
    // Free space
    lines.push(`GN  -1  0  0  0  0.0  0.0`);
  }

  lines.push(`RP  0  37  73  1000  0  0  5  5`);
  lines.push(`EN`);

  return lines.join('\n');
}
